import {
  Award,
  Box,
  ChartColumn,
  ClipboardCheck,
  HeartHandshake,
  House,
  LayoutDashboard,
  Library,
  ListChecks,
  Megaphone,
  Palette,
  Settings,
  ShieldCheck,
  SquareCheckBig,
  TrendingUp,
  UserRound,
  UsersRound,
  Waypoints,
  type LucideIcon,
} from "lucide-react";
import type { NavIcon } from "./nav-config";

export const NAV_ICONS: Record<NavIcon, LucideIcon> = {
  home: House,
  courses: Box,
  paths: Waypoints,
  development: TrendingUp,
  surveys: SquareCheckBig,
  announcements: Megaphone,
  library: Library,
  profile: UserRound,
  achievements: Award,
  dashboard: LayoutDashboard,
  users: UsersRound,
  content: ClipboardCheck,
  assessments: ListChecks,
  engagement: HeartHandshake,
  reports: ChartColumn,
  settings: Settings,
  audit: ShieldCheck,
  customization: Palette,
};
